import warnings

# Canonical name → list of known aliases
# Canonical form matches BartTorvik naming conventions
TEAM_ALIASES: dict[str, list[str]] = {
    # A — including SBRO concatenated forms
    "Alabama": ["Alabama Crimson Tide", "Ala.", "Alabama"],
    "Arizona": ["Arizona Wildcats", "Ariz."],
    "Arizona State": ["Arizona St.", "Arizona St", "ASU", "Arizona State Sun Devils", "ArizonaSt", "ArizonaState"],
    "Arkansas": ["Arkansas Razorbacks", "Ark.", "ArkansasLittleRock"],
    "Auburn": ["Auburn Tigers"],

    # B
    "Baylor": ["Baylor Bears"],
    "Belmont": ["Belmont Bruins"],
    "BYU": ["Brigham Young", "Brigham Young Cougars", "Brigham Young University", "BrighamYoung"],
    "Boise State": ["Boise St.", "Boise St", "Boise State Broncos", "BoiseSt"],
    "Buffalo": ["UB", "Buffalo Bulls"],

    # C
    "California": ["Cal", "Cal Bears", "California Golden Bears"],
    "Cincinnati": ["Cincinnati Bearcats"],
    "Clemson": ["Clemson Tigers"],
    "Cleveland State": ["Cleveland St.", "Cleveland State Vikings"],
    "Colgate": ["Colgate Raiders"],
    "Colorado": ["Colorado Buffaloes"],
    "Colorado State": ["Colorado St.", "Colorado St", "Colorado State Rams"],
    "Connecticut": ["UConn", "Connecticut Huskies", "UCONN", "Conn."],
    "Creighton": ["Creighton Bluejays"],

    # D
    "Davidson": ["Davidson Wildcats"],
    "Dayton": ["Dayton Flyers"],
    "Drake": ["Drake Bulldogs"],
    "Duke": ["Duke Blue Devils"],

    # E
    "East Tennessee State": ["ETSU", "East Tennessee St.", "East Tennessee State Buccaneers"],

    # F
    "Florida": ["Florida Gators", "Fla."],
    "Florida Atlantic": ["FAU", "Florida Atlantic Owls"],
    "Florida State": ["Florida St.", "Florida St", "FSU", "Florida State Seminoles"],
    "Furman": ["Furman Paladins"],

    # G
    "Georgia": ["Georgia Bulldogs", "Ga."],
    "Georgia State": ["Georgia St.", "Georgia St", "Georgia State Panthers"],
    "Gonzaga": ["Gonzaga Bulldogs", "Zags"],
    "Grand Canyon": ["GCU", "Grand Canyon Antelopes"],

    # H
    "Harvard": ["Harvard Crimson"],
    "Houston": ["Houston Cougars"],

    # I
    "Illinois": ["Illinois Fighting Illini", "Ill."],
    "Indiana": ["Indiana Hoosiers", "Ind."],
    "Iowa": ["Iowa Hawkeyes"],
    "Iowa State": ["Iowa St.", "Iowa St", "Iowa State Cyclones"],

    # J
    "James Madison": ["JMU", "James Madison Dukes"],

    # K
    "Kansas": ["Kansas Jayhawks", "KU"],
    "Kansas State": ["Kansas St.", "Kansas St", "K-State", "Kansas State Wildcats"],
    "Kentucky": ["Kentucky Wildcats", "UK"],

    # L
    "Liberty": ["Liberty Flames"],
    "Louisiana Lafayette": ["Louisiana", "UL Lafayette", "Louisiana Ragin' Cajuns", "Louisiana-Lafayette"],
    "LSU": ["Louisiana State", "Louisiana St.", "LSU Tigers"],
    "Louisville": ["Louisville Cardinals"],
    "Loyola Chicago": ["Loyola-Chicago", "Loyola (IL)", "Loyola Chicago Ramblers"],

    # M
    "Marquette": ["Marquette Golden Eagles"],
    "Maryland": ["Maryland Terrapins", "Md."],
    "Memphis": ["Memphis Tigers"],
    "Miami FL": ["Miami", "Miami (FL)", "Miami Hurricanes", "Miami (Fla.)"],
    "Michigan": ["Michigan Wolverines", "Mich."],
    "Michigan State": ["Michigan St.", "Michigan St", "MSU", "Michigan State Spartans"],
    "Minnesota": ["Minnesota Golden Gophers", "Minn."],
    "Mississippi State": ["Mississippi St.", "Mississippi St", "Miss. St.", "Mississippi State Bulldogs"],
    "Missouri": ["Missouri Tigers", "Mizzou"],
    "Montana State": ["Montana St.", "Montana State Bobcats"],
    "Morehead State": ["Morehead St.", "Morehead State Eagles"],
    "Murray State": ["Murray St.", "Murray State Racers"],

    # N
    "Nebraska": ["Nebraska Cornhuskers"],
    "Nevada": ["Nevada Wolf Pack"],
    "New Mexico State": ["New Mexico St.", "NMSU", "New Mexico State Aggies"],
    "North Carolina": ["UNC", "North Carolina Tar Heels", "NC", "N. Carolina"],
    "North Carolina State": ["NC State", "N.C. State", "NC St.", "NC State Wolfpack", "North Carolina St."],
    "North Texas": ["North Texas Mean Green"],
    "Northwestern": ["Northwestern Wildcats"],
    "Notre Dame": ["Notre Dame Fighting Irish", "ND"],

    # O
    "Ohio State": ["Ohio St.", "Ohio St", "OSU", "Ohio State Buckeyes"],
    "Oklahoma": ["Oklahoma Sooners", "OU"],
    "Oklahoma State": ["Oklahoma St.", "Oklahoma St", "Okla. St.", "Oklahoma State Cowboys"],
    "Ole Miss": ["Mississippi", "Mississippi Rebels"],
    "Oregon": ["Oregon Ducks"],
    "Oregon State": ["Oregon St.", "Oregon St", "Oregon State Beavers"],

    # P
    "Penn State": ["Penn St.", "Penn St", "Pennsylvania State", "Penn State Nittany Lions"],
    "Pittsburgh": ["Pitt", "Pittsburgh Panthers"],
    "Purdue": ["Purdue Boilermakers"],
    "Purdue Fort Wayne": ["IPFW", "Purdue Fort Wayne Mastodons"],

    # R
    "Richmond": ["Richmond Spiders"],
    "Rutgers": ["Rutgers Scarlet Knights"],

    # S
    "Saint Mary's": ["St. Mary's", "Saint Mary's (CA)", "SMC", "St. Mary's (CA)", "Saint Mary's Gaels"],
    "Saint Peter's": ["St. Peter's", "Saint Peter's Peacocks"],
    "San Diego State": ["SDSU", "San Diego St.", "San Diego State Aztecs"],
    "South Carolina": ["South Carolina Gamecocks", "S. Carolina"],
    "Southern Illinois": ["SIU", "Southern Illinois Salukis"],
    "Stanford": ["Stanford Cardinal"],
    "Syracuse": ["Syracuse Orange"],

    # T
    "TCU": ["Texas Christian", "Texas Christian Horned Frogs"],
    "Temple": ["Temple Owls"],
    "Tennessee": ["Tennessee Volunteers", "Tenn."],
    "Texas": ["Texas Longhorns", "UT"],
    "Texas A&M": ["Texas A&M Aggies", "TAMU"],
    "Texas Southern": ["Texas Southern Tigers"],
    "Texas Tech": ["Texas Tech Red Raiders"],
    "Toledo": ["Toledo Rockets"],
    "Troy": ["Troy Trojans"],
    "Tulsa": ["Tulsa Golden Hurricane"],

    # U
    "UCLA": ["UCLA Bruins", "UC Los Angeles"],
    "UNLV": ["Nevada Las Vegas", "Nevada-Las Vegas"],
    "USC": ["Southern California", "Southern Cal", "USC Trojans"],
    "Utah": ["Utah Utes"],
    "Utah State": ["Utah St.", "Utah St", "Utah State Aggies"],

    # V
    "Vanderbilt": ["Vanderbilt Commodores", "Vandy"],
    "Vermont": ["Vermont Catamounts"],
    "VCU": ["Virginia Commonwealth", "Virginia Commonwealth Rams"],
    "Virginia": ["Virginia Cavaliers", "UVA"],
    "Virginia Tech": ["Virginia Tech Hokies", "Va. Tech"],

    # W
    "Wake Forest": ["Wake Forest Demon Deacons"],
    "Washington": ["Washington Huskies", "Wash."],
    "Washington State": ["Washington St.", "Washington St", "Wazzu", "Washington State Cougars"],
    "West Virginia": ["WVU", "West Virginia Mountaineers", "W. Virginia"],
    "Western Kentucky": ["WKU", "Western Kentucky Hilltoppers"],
    "Wichita State": ["Wichita St.", "Wichita St", "Wichita State Shockers"],
    "Wisconsin": ["Wisconsin Badgers", "Wisc."],
    "Wright State": ["Wright St.", "Wright State Raiders"],
    "Wyoming": ["Wyoming Cowboys"],

    # X
    "Xavier": ["Xavier Musketeers"],

    # — Additional tournament teams (small/mid-majors) —
    "Abilene Christian": ["Abilene Christian Wildcats", "ACU"],
    "Alabama State": ["Alabama St.", "Alabama State Hornets"],
    "Appalachian State": ["App State", "App St.", "Appalachian St."],
    "Bradley": ["Bradley Braves"],
    "Bryant": ["Bryant Bulldogs"],
    "Cal State Fullerton": ["CS Fullerton", "CSFullerton", "Cal St. Fullerton", "Cal State Fullerton"],
    "Cal Baptist": ["Cal Baptist", "Cal Baptist Lancers"],
    "Central Michigan": ["Central Mich.", "Central Michigan Chippewas"],
    "Chattanooga": ["UTC", "Chattanooga Mocs"],
    "College of Charleston": ["Charleston", "Charleston Cougars"],
    "Delaware": ["Delaware Fightin Blue Hens"],
    "Eastern Washington": ["E. Washington", "E. Wash.", "Eastern Wash.", "Eastern Washington Eagles"],
    "FDU": ["Fairleigh Dickinson", "FairDickinson", "Fairleigh Dickinson Knights"],
    "Gardner-Webb": ["Gardner Webb", "GardnerWebb", "Gardner-Webb Runnin' Bulldogs"],
    "Georgia Tech": ["Georgia Tech Yellow Jackets", "GA Tech", "Ga. Tech"],
    "Hartford": ["Hartford Hawks"],
    "High Point": ["High Point Panthers"],
    "Hawaii": ["Hawai'i Rainbow Warriors", "Hawaii", "Hawai'i", "Hawaii Warriors"],
    "Idaho": ["Idaho Vandals"],
    "Jacksonville State": ["Jacksonville St.", "Jacksonville State Gamecocks"],
    "Lehigh": ["Lehigh Mountain Hawks"],
    "LIU": ["Long Island University", "LIU Sharks", "LIU Brooklyn", "LIU Brooklyn Sharks"],
    "Miami OH": ["Miami (OH)", "Miami (Ohio)", "Miami (OH) RedHawks", "Miami OH RedHawks", "Miami Ohio"],
    "Northern Iowa": ["Northern Iowa Panthers", "UNI"],
    "Siena": ["Siena Saints"],
    "Tennessee St.": ["Tennessee State", "Tennessee State Tigers", "Tennessee St. Tigers", "Tennessee St Tigers"],
    "Kennesaw State": ["Kennesaw St.", "Kennesaw State Owls"],
    "Kent State": ["Kent St.", "Kent State Golden Flashes"],
    "La Salle": ["LaSalle", "La Salle Explorers"],
    "Lipscomb": ["Lipscomb Bisons"],
    "Long Beach State": ["Long Beach St.", "CSULB", "Long Beach State Beach"],
    "Longwood": ["Longwood Lancers"],
    "Louisiana Tech": ["Louisiana Tech Bulldogs", "La. Tech"],
    "Loyola (MD)": ["Loyola Maryland", "Loyola MD", "LoyolaMaryland", "Loyola (Maryland)"],
    "McNeese State": ["McNeese St.", "McNeese State Cowboys"],
    "Memphis": ["Memphis Tigers", "MemphisU"],
    # "Miami FL" duplicate removed — full alias list is at line ~81
    "Middle Tennessee": ["Middle Tenn.", "MTSU", "Middle Tennessee Blue Raiders", "MiddleTennSt"],
    "Montana": ["Montana Grizzlies"],
    "Mount St. Mary's": ["Mount St. Mary's Mountaineers", "MtStMarys", "MountStMarys"],
    "New Mexico": ["UNM", "New Mexico Lobos", "NewMexico"],
    "Nicholls State": ["Nicholls St.", "Nicholls State Colonels", "NichollsState"],
    "Norfolk State": ["Norfolk St.", "Norfolk State Spartans", "NorfolkSt"],
    "North Carolina A&T": ["NC A&T", "North Carolina A&T Aggies", "N.CarolinaA&T"],
    "North Dakota State": ["North Dakota St.", "NDSU", "NorthDakotaState", "North Dakota State Bison"],
    "Northern Kentucky": ["NKU", "Northern Kentucky Norse", "NorthernKentucky"],
    "Oakland": ["Oakland Golden Grizzlies"],
    "Ohio": ["Ohio Bobcats"],
    "Old Dominion": ["ODU", "Old Dominion Monarchs", "OldDominion"],
    "Oral Roberts": ["ORU", "Oral Roberts Golden Eagles", "OralRoberts"],
    "Princeton": ["Princeton Tigers"],
    "Robert Morris": ["Robert Morris Colonials"],
    "SIU-Edwardsville": ["SIUE", "SIU Edwardsville Cougars"],
    "Saint Louis": ["Saint Louis Billikens", "SaintLouis", "St. Louis"],
    "Samford": ["Samford Bulldogs"],
    "San Francisco": ["USF", "San Francisco Dons"],
    "Seton Hall": ["Seton Hall Pirates", "SetonHall"],
    "South Carolina State": ["SC State", "South Carolina St.", "SoCarolinaSt"],
    "South Dakota State": ["SDSU", "South Dakota St.", "SouthDakotaState", "South Dakota State Jackrabbits"],
    "St. Bonaventure": ["St. Bonaventure Bonnies", "St.Bonaventure", "SaintBonaventure"],
    "St. John's (NY)": ["St. John's", "St. Johns", "St.Johns", "Saint John's", "St. John's Red Storm", "St John's"],
    "Stephen F. Austin": ["Stephen F. Austin Lumberjacks", "SFA Lumberjacks", "SF Austin"],
    "South Alabama": ["South Alabama Jaguars"],
    "St. Thomas": ["St. Thomas (MN) Tommies", "St. Thomas (MN)", "Saint Thomas"],
    "Navy": ["Navy Midshipmen"],
    "George Washington": ["GW Revolutionaries", "GW"],
    "Sam Houston": ["Sam Houston State", "Sam Houston Bearkats"],
    "Illinois-Chicago": ["UIC Flames", "UIC"],
    "Queens": ["Queens (NC)", "Queens NC"],
    "Stetson": ["Stetson Hatters"],
    "Texas A&M-Corpus Christi": ["TAMUCC", "Texas A&M Corpus Christi", "TexasA&MCorpus"],
    "UAB": ["Alabama-Birmingham", "UAB Blazers"],
    "UC-Irvine": ["UC Irvine", "UCI", "CalIrvine", "UC Irvine Anteaters"],
    "UC-San Diego": ["UCSD", "UC San Diego Tritons"],
    "UCF": ["Central Florida", "CentralFlorida", "UCF Knights"],
    "UCSB": ["UC Santa Barbara", "CalSantaBarb", "UC Santa Barbara Gauchos"],
    "UNC Asheville": ["UNCA", "UNC-Asheville", "Asheville"],
    "UNC Greensboro": ["UNCG", "UNC-Greensboro", "NCGreensboro", "UNC Greensboro Spartans"],
    "UNC Wilmington": ["UNCW", "UNC-Wilmington", "Wilmington"],
    "Utah Tech": ["Utah Tech Trailblazers"],
    # "Utah" duplicate removed — full alias list is at line ~144
    "Wagner": ["Wagner Seahawks"],
    "Winthrop": ["Winthrop Eagles"],
    "Wofford": ["Wofford Terriers"],
}

# SBRO-specific concatenated aliases (no spaces, e.g. "MichiganState")
# These are appended here so they don't clutter the main table above
_SBRO_EXTRA: dict[str, str] = {
    # A
    "alabama": "Alabama",
    "arizona": "Arizona",
    "arizonast": "Arizona State",
    "arizonastate": "Arizona State",
    "arkansas": "Arkansas",
    "auburn": "Auburn",
    # B
    "baylor": "Baylor",
    "brighamyoung": "BYU",
    "boisestate": "Boise State",
    "boisest": "Boise State",
    "buffalo": "Buffalo",
    "butler": "Butler",
    # C
    "california": "California",
    "cincinnati": "Cincinnati",
    "clemson": "Clemson",
    "colorado": "Colorado",
    "coloradost": "Colorado State",
    "coloradostate": "Colorado State",
    "connecticut": "Connecticut",
    "uconn": "Connecticut",
    "creighton": "Creighton",
    # D
    "davidson": "Davidson",
    "dayton": "Dayton",
    "duke": "Duke",
    # F
    "florida": "Florida",
    "floridaatlantic": "Florida Atlantic",
    "fau": "Florida Atlantic",
    "floridast": "Florida State",
    "floridastate": "Florida State",
    # G
    "gonzaga": "Gonzaga",
    "grandcanyon": "Grand Canyon",
    "georgia": "Georgia",
    "georgiastate": "Georgia State",
    "georgiast": "Georgia State",
    "georgiatech": "Georgia Tech",
    # H
    "houston": "Houston",
    # I
    "illinois": "Illinois",
    "indiana": "Indiana",
    "iowa": "Iowa",
    "iowast": "Iowa State",
    "iowastate": "Iowa State",
    # K
    "kansas": "Kansas",
    "kansasst": "Kansas State",
    "kansasstate": "Kansas State",
    "kentucky": "Kentucky",
    # L
    "loyolachicago": "Loyola Chicago",
    "lsu": "LSU",
    "louisville": "Louisville",
    # M
    "marquette": "Marquette",
    "maryland": "Maryland",
    "michigan": "Michigan",
    "michiganst": "Michigan State",
    "michiganstate": "Michigan State",
    "minnesota": "Minnesota",
    "mississippi": "Ole Miss",
    "mississippist": "Mississippi State",
    "mississippistate": "Mississippi State",
    "missourist": "Missouri",
    "missouri": "Missouri",
    "murrayst": "Murray State",
    "murraystate": "Murray State",
    # N
    "northcarolina": "North Carolina",
    "unc": "North Carolina",
    "northcarolinast": "North Carolina State",
    "ncstate": "North Carolina State",
    "notreDame": "Notre Dame",
    "notredame": "Notre Dame",
    "northtexas": "North Texas",
    "northwestern": "Northwestern",
    # O
    "ohiost": "Ohio State",
    "ohiostate": "Ohio State",
    "oklahoma": "Oklahoma",
    "oklahomost": "Oklahoma State",
    "oklahomastate": "Oklahoma State",
    "olemiss": "Ole Miss",
    "oregon": "Oregon",
    "oregonst": "Oregon State",
    "oregonstate": "Oregon State",
    # P
    "pennst": "Penn State",
    "pennstate": "Penn State",
    "pittsburgh": "Pittsburgh",
    "pitt": "Pittsburgh",
    "purdue": "Purdue",
    # R
    "richmond": "Richmond",
    "rutgers": "Rutgers",
    # S
    "saintmarys": "Saint Mary's",
    "stmarys": "Saint Mary's",
    "saintmarysca": "Saint Mary's",
    "stmarysca": "Saint Mary's",
    "moreheadstate": "Morehead State",
    "moreheadst": "Morehead State",
    "saintpeters": "Saint Peter's",
    "sandiegustate": "San Diego State",
    "sandiegostate": "San Diego State",
    "sdsu": "San Diego State",
    "southcarolina": "South Carolina",
    "stanford": "Stanford",
    "syracuse": "Syracuse",
    # T
    "tcu": "TCU",
    "tennessee": "Tennessee",
    "texas": "Texas",
    "texasam": "Texas A&M",
    "texastech": "Texas Tech",
    "texassouthern": "Texas Southern",
    # U
    "ucla": "UCLA",
    "usc": "USC",
    "utah": "Utah",
    "utahstate": "Utah State",
    "utahst": "Utah State",
    # V
    "vanderbilt": "Vanderbilt",
    "vcu": "VCU",
    "virginiacommonwealth": "VCU",
    "virginia": "Virginia",
    "virginiatech": "Virginia Tech",
    # W
    "wakeforest": "Wake Forest",
    "washington": "Washington",
    "washingtonst": "Washington State",
    "washingtonstate": "Washington State",
    "westvirginia": "West Virginia",
    "wvu": "West Virginia",
    "wichitast": "Wichita State",
    "wichitastate": "Wichita State",
    "wisconsin": "Wisconsin",
    # X
    "xavier": "Xavier",

    # — SBRO concatenated names for small/mid-major teams —
    "abilenechristian": "Abilene Christian",
    "alabamastate": "Alabama State",
    "alabamast": "Alabama State",
    "appalachianst": "Appalachian State",
    "appalachianstate": "Appalachian State",
    "bradley": "Bradley",
    "bryant": "Bryant",
    "csfullerton": "Cal State Fullerton",
    "calstatefullerton": "Cal State Fullerton",
    "centralmichigan": "Central Michigan",
    "centralflorida": "UCF",
    "ucf": "UCF",
    "chattanooga": "Chattanooga",
    "charlestonsu": "College of Charleston",
    "charlestonsou": "College of Charleston",
    "collegeofcharleston": "College of Charleston",
    "cleveland state": "Cleveland State",
    "clevelandstate": "Cleveland State",
    "coastalcarolina": "Coastal Carolina",
    "delaware": "Delaware",
    "e.washington": "Eastern Washington",
    "easternwashington": "Eastern Washington",
    "fairdickinson": "FDU",
    "fairleighdickinson": "FDU",
    "fdu": "FDU",
    "gardnerwebb": "Gardner-Webb",
    "georgiatech": "Georgia Tech",
    "hartford": "Hartford",
    "highpoint": "High Point",
    "houstonbaptist": "Houston Baptist",
    "houstonu": "Houston",
    "indianau": "Indiana",
    "jacksonvillest": "Jacksonville State",
    "jacksonvillestate": "Jacksonville State",
    "kennesawstate": "Kennesaw State",
    "kennesawst": "Kennesaw State",
    "kentstate": "Kent State",
    "kentst": "Kent State",
    "lasalle": "La Salle",
    "lipscomb": "Lipscomb",
    "longbeachstate": "Long Beach State",
    "longbeachst": "Long Beach State",
    "longwood": "Longwood",
    "louisianatech": "Louisiana Tech",
    "loyolamaryland": "Loyola (MD)",
    "loyolamd": "Loyola (MD)",
    "mcneesesstate": "McNeese State",
    "mcneesestate": "McNeese State",
    "memphisu": "Memphis",
    "miamiflorida": "Miami FL",
    "middletennst": "Middle Tennessee",
    "middletennessee": "Middle Tennessee",
    "minnesoatu": "Minnesota",
    "minnesotau": "Minnesota",
    "montana": "Montana",
    "mountstmarys": "Mount St. Mary's",
    "mtstmarys": "Mount St. Mary's",
    "ncgreensboro": "UNC Greensboro",
    "newmexico": "New Mexico",
    "newmexicostate": "New Mexico State",
    "newmexicost": "New Mexico State",
    "nichollsstate": "Nicholls State",
    "nichollsst": "Nicholls State",
    "norfolkst": "Norfolk State",
    "norfolkstate": "Norfolk State",
    "northcarolina at": "North Carolina A&T",
    "ncat": "North Carolina A&T",
    "n.carolinaat": "North Carolina A&T",
    "northdakotastate": "North Dakota State",
    "northdakotast": "North Dakota State",
    "northernkentucky": "Northern Kentucky",
    "nku": "Northern Kentucky",
    "oakland": "Oakland",
    "ohio": "Ohio",
    "olddominion": "Old Dominion",
    "odu": "Old Dominion",
    "oralroberts": "Oral Roberts",
    "oru": "Oral Roberts",
    "princeton": "Princeton",
    "robertmorris": "Robert Morris",
    "saintlouis": "Saint Louis",
    "samford": "Samford",
    "sanfrancisco": "San Francisco",
    "setonhall": "Seton Hall",
    "siuedwardsville": "SIU-Edwardsville",
    "siue": "SIU-Edwardsville",
    "socarolinast": "South Carolina State",
    "southcarolinast": "South Carolina State",
    "southdakotastate": "South Dakota State",
    "southdakotast": "South Dakota State",
    "st.bonaventure": "St. Bonaventure",
    "stbonaventure": "St. Bonaventure",
    "saintbonaventure": "St. Bonaventure",
    "st.johns": "St. John's (NY)",
    "stjohns": "St. John's (NY)",
    "saintjohns": "St. John's (NY)",
    "stetson": "Stetson",
    "texasamcorpus": "Texas A&M-Corpus Christi",
    "texasa&mcorpus": "Texas A&M-Corpus Christi",
    "uab": "UAB",
    "uc-irvine": "UC-Irvine",
    "ucirvine": "UC-Irvine",
    "calirvine": "UC-Irvine",
    "uc-sandiego": "UC-San Diego",
    "ucsandiego": "UC-San Diego",
    "ucsb": "UCSB",
    "calsantabarb": "UCSB",
    "uncasheville": "UNC Asheville",
    "uncgreensboro": "UNC Greensboro",
    "uncwilmington": "UNC Wilmington",
    "utahu": "Utah",
    "utahvalley": "Utah Valley",
    "vacommonwealth": "VCU",
    "wagner": "Wagner",
    "washingtonst": "Washington State",
    "washingtonu": "Washington",
    "winthrop": "Winthrop",
    "wofford": "Wofford",
    "wrightstate": "Wright State",
    "wrightst": "Wright State",
    "wyoming": "Wyoming",
}

# ── The Odds API abbreviated team name mappings ─────────────────────────────
# API uses "St " (no period) instead of "State", and other short forms.
# Key = lowercased API name, value = canonical name.
_ODDS_API_EXTRA: dict[str, str] = {
    # "St" → "State" abbreviations
    "arizona st sun devils": "Arizona State",
    "cleveland st vikings": "Cleveland State",
    "colorado st rams": "Colorado State",
    "florida st seminoles": "Florida State",
    "georgia st panthers": "Georgia State",
    "grambling st tigers": "Grambling State",
    "illinois st redbirds": "Illinois State",
    "indiana st sycamores": "Indiana State",
    "jacksonville st gamecocks": "Jacksonville State",
    "kansas st wildcats": "Kansas State",
    "kennesaw st owls": "Kennesaw State",
    "long beach st 49ers": "Long Beach State",
    "michigan st spartans": "Michigan State",
    "mississippi st bulldogs": "Mississippi State",
    "montana st bobcats": "Montana State",
    "morehead st eagles": "Morehead State",
    "murray st racers": "Murray State",
    "new mexico st aggies": "New Mexico State",
    "norfolk st spartans": "Norfolk State",
    "north carolina st wolfpack": "North Carolina State",
    "oklahoma st cowboys": "Oklahoma State",
    "oregon st beavers": "Oregon State",
    "san diego st aztecs": "San Diego State",
    "san jose st spartans": "San José State",
    "san josé st spartans": "San José State",
    "south dakota st jackrabbits": "South Dakota State",
    "utah st aggies": "Utah State",
    "washington st cougars": "Washington State",
    "wright st raiders": "Wright State",
    "alabama st hornets": "Alabama State",
    "chicago st cougars": "Chicago State",
    "delaware st hornets": "Delaware State",
    "north carolina a&t aggies": "North Carolina A&T",
    "sam houston st bearkats": "Sam Houston State",
    # 2026 NCAA Tournament — odds API full-name variants with mascots
    "st. john's red storm": "St. John's (NY)",
    "stephen f. austin lumberjacks": "Stephen F. Austin",
    "south alabama jaguars": "South Alabama",
    "st. thomas (mn) tommies": "St. Thomas",
    "navy midshipmen": "Navy",
    "george washington revolutionaries": "GW Revolutionaries",
    "uic flames": "Illinois-Chicago",
    "lehigh mountain hawks": "Lehigh",
    "lehigh mountain hawks lehigh": "Lehigh",
    "liu sharks": "LIU",
    "liu brooklyn sharks": "LIU",
    "northern iowa panthers": "Northern Iowa",
    "tennessee st tigers": "Tennessee St.",
    "tennessee state tigers": "Tennessee St.",
    "siena saints": "Siena",
    "idaho vandals": "Idaho",
    "miami (oh) redhawks": "Miami OH",
    "miami oh redhawks": "Miami OH",
    "north dakota st bison": "North Dakota State",
    "north carolina st wolfpack": "North Carolina State",
    "cal baptist lancers": "Cal Baptist",
    "high point panthers": "High Point",
    "hawaii rainbow warriors": "Hawaii",
    "hawaii warriors": "Hawaii",
    "kennesaw state owls": "Kennesaw State",
    "queens (nc) royals": "Queens (NC)",
    "queens royals": "Queens (NC)",
    "troy trojans": "Troy",
    "hofstra pride": "Hofstra",
    "wright state raiders": "Wright State",
    "akron zips": "Akron",
    "saint louis billikens": "Saint Louis",
    "santa clara broncos": "Santa Clara",
    "howard bison": "Howard",
    "furman paladins": "Furman",
    "sam houston bearkats": "Sam Houston",
    # School / nickname variants
    "byū cougars": "BYU",
    "byu cougars": "BYU",
    "uconn huskies": "Connecticut",
    "loyola (chi) ramblers": "Loyola Chicago",
    "ole miss rebels": "Ole Miss",
    "vcu rams": "VCU",
    "tcu horned frogs": "TCU",
    "smu mustangs": "SMU",
    "unlv rebels": "UNLV",
    "miami hurricanes": "Miami FL",
    # Ivy League / SWAC / mid-major full names with mascots
    "cornell big red": "Cornell",
    "cornell": "Cornell",
    "umbc retrievers": "UMBC",
    "umbc": "UMBC",
    "north carolina central eagles": "North Carolina Central",
    "north carolina central": "North Carolina Central",
    "nc central eagles": "North Carolina Central",
    "pennsylvania quakers": "Penn",
    "pennsylvania": "Penn",
    "penn quakers": "Penn",
    "saint joseph's hawks": "Saint Joseph's",
    "st. joseph's hawks": "Saint Joseph's",
    "st. joseph's": "Saint Joseph's",
    "wichita st shockers": "Wichita State",
    "wichita state shockers": "Wichita State",
    "southern jaguars": "Southern",
    "southern university": "Southern",
    "prairie view panthers": "Prairie View A&M",
    "prairie view a&m panthers": "Prairie View A&M",
    "prairie view": "Prairie View A&M",
    # Teams with nicknames not yet in TEAM_ALIASES
    "villanova wildcats": "Villanova",
    "villanova": "Villanova",
    "akron zips": "Akron",
    "akron": "Akron",
    "providence friars": "Providence",
    "providence": "Providence",
    "drexel dragons": "Drexel",
    "drexel": "Drexel",
    "iona gaels": "Iona",
    "iona": "Iona",
    "georgetown hoyas": "Georgetown",
    "georgetown": "Georgetown",
    "davidson wildcats": "Davidson",
    "yale bulldogs": "Yale",
    "yale": "Yale",
    "duquesne dukes": "Duquesne",
    "duquesne": "Duquesne",
    "howard bison": "Howard",
    "howard": "Howard",
    "army knights": "Army",
    "army": "Army",
    "boston college eagles": "Boston College",
    "boston college": "Boston College",
    "elon phoenix": "Elon",
    "elon": "Elon",
    "rice owls": "Rice",
    "rice": "Rice",
    "quinnipiac bobcats": "Quinnipiac",
    "quinnipiac": "Quinnipiac",
    "santa clara broncos": "Santa Clara",
    "santa clara": "Santa Clara",
    "seattle redhawks": "Seattle",
    "seattle": "Seattle",
    "hofstra pride": "Hofstra",
    "hofstra": "Hofstra",
    "omaha mavericks": "Nebraska-Omaha",
    "omaha": "Nebraska-Omaha",
    "charlotte 49ers": "Charlotte",
    "charlotte": "Charlotte",
    "incarnate word cardinals": "Incarnate Word",
    "incarnate word": "Incarnate Word",
    "tarleton state texans": "Tarleton State",
    "tarleton state": "Tarleton State",
    "texas a&m-cc islanders": "Texas A&M-Corpus Christi",
    "texas a&m corpus christi islanders": "Texas A&M-Corpus Christi",
    "queens university royals": "Queens (NC)",
    "queens university": "Queens (NC)",
    "alabama a&m bulldogs": "Alabama A&M",
    "alabama a&m": "Alabama A&M",
    "eastern kentucky colonels": "Eastern Kentucky",
    "eastern kentucky": "Eastern Kentucky",
    "evansville purple aces": "Evansville",
    "evansville": "Evansville",
    "fairfield stags": "Fairfield",
    "fairfield": "Fairfield",
    "george mason patriots": "George Mason",
    "george mason": "George Mason",
    "illinois state redbirds": "Illinois State",
    "illinois state": "Illinois State",
    "manhattan jaspers": "Manhattan",
    "manhattan": "Manhattan",
    "mcneese cowboys": "McNeese State",
    "mt. st. mary's mountaineers": "Mount St. Mary's",
    "northern arizona lumberjacks": "Northern Arizona",
    "northern arizona": "Northern Arizona",
    "presbyterian blue hose": "Presbyterian",
    "presbyterian": "Presbyterian",
    "radford highlanders": "Radford",
    "radford": "Radford",
    "csu fullerton titans": "Cal State Fullerton",
    "south florida bulls": "South Florida",
    "south florida": "South Florida",
    "southern indiana screaming eagles": "Southern Indiana",
    "southern indiana": "Southern Indiana",
    "southern utah thunderbirds": "Southern Utah",
    "southern utah": "Southern Utah",
    "unc asheville bulldogs": "UNC Asheville",
    "unc wilmington seahawks": "UNC Wilmington",
    "arkansas st red wolves": "Arkansas State",
    "arkansas state red wolves": "Arkansas State",
    "arkansas state": "Arkansas State",
    "arkansas-little rock trojans": "Little Rock",
    "delaware blue hens": "Delaware",
    "fort wayne mastodons": "Purdue Fort Wayne",
    "bethune-cookman wildcats": "Bethune-Cookman",
    "bethune cookman wildcats": "Bethune-Cookman",
    "utah valley wolverines": "Utah Valley",
    "western carolina catamounts": "Western Carolina",
    "western carolina": "Western Carolina",
    "n colorado bears": "Northern Colorado",
    "northern colorado bears": "Northern Colorado",
    "south carolina upstate spartans": "USC Upstate",
    # NIT team name variants — Odds API "St" abbreviations
    "alcorn st braves": "Alcorn State",
    "alcorn state braves": "Alcorn State",
    "youngstown st penguins": "Youngstown State",
    "appalachian st mountaineers": "Appalachian State",
    # NIT team name variants — ESPN full mascot names not yet in map
    "youngstown state penguins": "Youngstown State",
    "alcorn state braves": "Alcorn State",
    "app state mountaineers": "Appalachian State",
    "indiana state sycamores": "Indiana State",
    "butler bulldogs": "Butler",
    "missouri state bears": "Missouri State",
    "nicholls colonels": "Nicholls State",
    "nicholls st colonels": "Nicholls State",
    "towson tigers": "Towson",
    "north alabama lions": "North Alabama",
    "saint francis red flash": "Saint Francis (PA)",
    "southern miss golden eagles": "Southern Miss",
    "morehead state eagles": "Morehead State",
    "morehead st eagles": "Morehead State",
    "san josé state spartans": "San José State",
    "san jose state spartans": "San José State",
}

# Add new canonical entries for teams not in TEAM_ALIASES
_NEW_CANONICALS: dict[str, str] = {
    "Villanova": "Villanova",
    "Akron": "Akron",
    "Providence": "Providence",
    "Drexel": "Drexel",
    "Iona": "Iona",
    "Georgetown": "Georgetown",
    "Yale": "Yale",
    "Duquesne": "Duquesne",
    "Howard": "Howard",
    "Army": "Army",
    "Boston College": "Boston College",
    "Elon": "Elon",
    "Rice": "Rice",
    "Quinnipiac": "Quinnipiac",
    "Santa Clara": "Santa Clara",
    "Seattle": "Seattle",
    "Hofstra": "Hofstra",
    "Nebraska-Omaha": "Nebraska-Omaha",
    "Charlotte": "Charlotte",
    "Incarnate Word": "Incarnate Word",
    "Tarleton State": "Tarleton State",
    "Queens (NC)": "Queens (NC)",
    "Alabama A&M": "Alabama A&M",
    "Eastern Kentucky": "Eastern Kentucky",
    "Evansville": "Evansville",
    "Fairfield": "Fairfield",
    "George Mason": "George Mason",
    "Illinois State": "Illinois State",
    "Manhattan": "Manhattan",
    "Northern Arizona": "Northern Arizona",
    "Presbyterian": "Presbyterian",
    "Radford": "Radford",
    "South Florida": "South Florida",
    "Southern Indiana": "Southern Indiana",
    "Southern Utah": "Southern Utah",
    "Arkansas State": "Arkansas State",
    "Little Rock": "Little Rock",
    "Bethune-Cookman": "Bethune-Cookman",
    "Utah Valley": "Utah Valley",
    "Western Carolina": "Western Carolina",
    "Northern Colorado": "Northern Colorado",
    "USC Upstate": "USC Upstate",
    "SMU": "SMU",
    "Sam Houston State": "Sam Houston State",
    "San José State": "San José State",
    "Grambling State": "Grambling State",
    "Chicago State": "Chicago State",
    "Delaware State": "Delaware State",
    "Indiana State": "Indiana State",
    "North Carolina A&T": "North Carolina A&T",
    # NIT canonicals not previously in map
    "Youngstown State": "Youngstown State",
    "Alcorn State": "Alcorn State",
    "Missouri State": "Missouri State",
    "Towson": "Towson",
    "North Alabama": "North Alabama",
    "Southern Miss": "Southern Miss",
    "Morehead State": "Morehead State",
    # Ivy / mid-major canonicals
    "Cornell": "Cornell",
    "UMBC": "UMBC",
    "North Carolina Central": "North Carolina Central",
    "Penn": "Penn",
    "Saint Joseph's": "Saint Joseph's",
    "Southern": "Southern",
    "Prairie View A&M": "Prairie View A&M",
}

# Build reverse lookup: alias → canonical
_ALIAS_TO_CANONICAL: dict[str, str] = {}
for canonical, aliases in TEAM_ALIASES.items():
    _ALIAS_TO_CANONICAL[canonical.lower()] = canonical
    for alias in aliases:
        _ALIAS_TO_CANONICAL[alias.lower()] = canonical
# Add SBRO extras
for sbro_key, canonical in _SBRO_EXTRA.items():
    _ALIAS_TO_CANONICAL[sbro_key.lower()] = canonical
# Add Odds API extras
for odds_key, canonical in _ODDS_API_EXTRA.items():
    _ALIAS_TO_CANONICAL[odds_key.lower()] = canonical
# Add new canonicals (self-resolving)
for canonical in _NEW_CANONICALS:
    _ALIAS_TO_CANONICAL[canonical.lower()] = canonical


def normalize_team_name(raw_name: str) -> str:
    """Map any alias to canonical name. Issues a warning if unknown."""
    if not raw_name:
        return raw_name
    key = raw_name.strip().lower()
    result = _ALIAS_TO_CANONICAL.get(key)
    if result is None:
        warnings.warn(f"Unknown team name: '{raw_name}' — returning as-is", stacklevel=2)
        return raw_name
    return result


def get_all_canonical_names() -> list[str]:
    return sorted(TEAM_ALIASES.keys())


def is_known_team(name: str) -> bool:
    return name.strip().lower() in _ALIAS_TO_CANONICAL
